Implementação do Bubble Sort
ProfDudarts/ordenacao pull request #1
Opened 2024-10-18 01:07 UTC by ptgz

Caro Dev Senior,

Gostaria que visualizasse e verifique se meu código está correto. Caso esteja, que tome as decisões necessárias e aceite este pull request de um mero faixa transparente do código.

At.te,
Grupo 01

2024-10-18 01:11 UTC, ProfDudarts requested changes
Por favor, faça as mudanças indicadas nos comentários.

2024-10-18 01:11 UTC, ProfDudarts commented on lib/ordenacao.py
> +    for i in range(len(list)):
add o len(list) em uma variável para não repetir o comando.

2024-10-18 01:11 UTC, ProfDudarts commented on lib/ordenacao.py
> +    return list
Não é para retornar a lista, apenas para alterar a lista enviada no parâmetro.

2024-10-18 01:11 UTC, ProfDudarts commented on lib/ordenacao.py
> +    return list
Adicione um variável para verificar se a lista já está ordenada. Pode considerar que está ordenanda quando não houver trocas de posições na lista.

2024-10-18 01:32 UTC, ptgz commented on lib/ordenacao.py
> +    return list
OK

2024-10-18 01:32 UTC, ptgz commented on lib/ordenacao.py
> +    return list
OK

2024-10-24 13:45 UTC, dudarts approved these changes

2024-10-24 13:45 UTC, dudarts approved these changes

2024-10-24 13:58 UTC, ProfDudarts approved these changes

2024-10-24 14:00 UTC, merged