Function bubble_sort() added
ProfDudarts/ordenacao pull request #7
Opened 2024-10-18 17:16 UTC by LucionOne

2024-10-18 17:25 UTC, LucionOne commented
por algum motivo não tenho alguma permissão, então fiz um fork e um pull request a parti do fork

2024-10-18 18:26 UTC, LucionOne commented
aparentemente não funciona com "return" então fiz uma gambiarra

2024-10-24 14:05 UTC, ProfDudarts requested changes

2024-10-24 14:05 UTC, ProfDudarts commented on lib/ordenacao.py
> +    def sort(vector: list) -> list:
Não há necessidade de criar uma função dentro da outra. Isto deixa o código mais complexo de enteder. Simplique a solução.

2024-10-24 14:05 UTC, ProfDudarts commented on lib/ordenacao.py
> +        def compare(a: float, b: float):
O mesmo aqui. Não há necessidade de criar uma função dentro da outra. Isto deixa o código mais complexo de enteder. Simplique a solução.

Se desejar criar uma função auxiliar, crie-a fora do escopo da função bublle_sort, assim, ele ficaria disponível para ser executa

2024-10-24 14:05 UTC, ProfDudarts commented on testes.py
>      {
Não é para alterar o arquivo de teste. Ele é para ser executado do jeito que estava. Se a implementação estiver correta, os testes passarão com sucesso.

2024-10-25 00:39 UTC, closed without merging